### PR TITLE
Update broken WTF links

### PR DESCRIPTION
**Pull request by jayzes**
Corollary to https://github.com/ello/wtf/pull/96

### CODE REVIEW

**Comment by ellodanger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a linked tracker story for this PR in the description</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Nice, more deletions than insertions :red_circle:</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by jayzes** [comment]
@caseydoran good call - fixed in https://github.com/ello/wtf/pull/96/commits/ea9ee05153916d8ebbd2acd04bf902d48b086624. That'll let us do redirects in wtf moving forward too, which is nice.

**Comment by jayzes** [comment]
I actually might take a look at pulling the wtf redirects out of the frontend gateway too while i'm at it.

**Comment by caseydoran** [comment]
Nice. 👍

**Pull request merged**
