### PR TITLE
All yarn all the time

### PR DESCRIPTION
**Pull request by mkitt**
This just updates the calls in the package.json scripts. 

This PR is using the immutable branch as the base branch.

### CODE REVIEW

**Comment by jayzes** [comment]
How is there no :ball_of_yarn: emoji?

**Comment by mkitt** [comment]
Good call @rynbyjn I'll add that here.

**Comment by mkitt** [comment]
@rynbyjn tweaked the Dockerfile as well.

**Comment by mkitt** [comment]
Totally. Might actually wait till Monday on merging this one. I'm not sure I want to spend tomorrow messing with heroku from the 🏔. 🐹

**Comment by mkitt** [comment]
Closing in favor of #103

**Pull request closed without merging**
