### PR TITLE
Artist Invites: Card Height / Description Tweaks

### PR DESCRIPTION
**Pull request by gblakeman**
https://www.pivotaltracker.com/story/show/150095755
https://www.pivotaltracker.com/story/show/151502062

### CODE REVIEW

**Comment by ellodanger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Nice, more deletions than insertions :red_circle:</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by gblakeman** [comment]
@alanpeabody Sorry, this is still `wip` but @ellodanger added the `please review` label – how can avoid that? Should I just wait until I’m ready to start a PR?

**Comment by alanpeabody** [comment]
@gblakeman if you add WIP to the PR title it won't add the needs review.

**Comment by gblakeman** [comment]
@alanpeabody Ah, gotcha. 👌 I’d been adding the label, but not in the title.

**Comment by alanpeabody** [comment]
:+1:

**Comment by gblakeman** [comment]
@alanpeabody I changed my approach to this a bit, so you might want to take a peak again. Good news is that’s all CSS-based changes with a tiny bit of changed markup.

**Pull request merged**
