### PR TITLE
[ED-162] - fix duplicate user badges on profile page

### PR DESCRIPTION
**Pull request by TahaMaqbool**

### CODE REVIEW

**Comment by usmanchaudhryme** [comment]
Also, there are failing specs. Please make sure there aren't any failing ones.

**Comment by TahaMaqbool** [comment]
> Looks pretty solid, awesome! If possible add a selector spec as well, and simply pass it the duplicated ones and it should still return without any duplicates.
> 
> All else looks great.



> Looks pretty solid, awesome! If possible add a selector spec as well, and simply pass it the duplicated ones and it should still return without any duplicates.
> 
> All else looks great.

Added those specs suggested.

**Comment by TahaMaqbool** [comment]
> Also, there are failing specs. Please make sure there aren't any failing ones.

Fixed, now got to know about the specs code so would make sure onwards. Thanks.

**Comment by usmanchaudhryme** [comment]
Awesome! Looks great, please merge accordingly.

**Pull request merged**
