### PR TITLE
Ads NFP to footer

### PR DESCRIPTION
**Pull request by caseydoran**
not sure if there is a spec for this that I may be missing

### CODE REVIEW

**Comment by ellodanger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a linked tracker story for this PR in the description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mkitt** [comment]
Looks like you have a linting error @caseydoran https://travis-ci.org/ello/webapp/builds/211553795

**Comment by caseydoran** [comment]
@mkitt I changed it to single quotes, hopefully that'll work. If not I may need a hand. Thanks!

**Comment by caseydoran** [comment]
putting in for another review pre-merge just in case

**Pull request merged**
