### PR TITLE
Post redirect issue

### PR DESCRIPTION
**Pull request by ansh-k**
closes https://jiraeyeem.atlassian.net/browse/ED-22

### CODE REVIEW

**Review by usmanchaudhryme — CHANGES_REQUESTED** [review]
Looks in good shape, can you also add some specs?

**Comment by ansh-k** [comment]
> Looks in good shape, can you also add some specs?

Sure

**Comment by ansh-k** [comment]
> Looks in good shape, can you also add some specs?

Added test case

**Review by usmanchaudhryme — APPROVED** [review]
Looks good now, please merge accordingly.

**Pull request merged**
