### PR TITLE
Update the UI of the editor

### PR DESCRIPTION
**Pull request by rynbyjn**
[#147889065](https://www.pivotaltracker.com/story/show/147889065)

### CODE REVIEW

**Comment by ellodanger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Nice, more deletions than insertions :red_circle:</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by rynbyjn** [comment]
@alanpeabody @Justin-Holmes @colinta there is a bunch of css and jso style updates in this PR, not sure if y'all wanted to take a look before I merge it.

**Comment by rynbyjn** [comment]
I have to be honest though, css is kinda hard to review without just looking at it in a browser. You kind of look at it and say "ok, I guess that change looks like it works for that button with all of the various media queries, LGTM".

**Comment by Justin-Holmes** [comment]
LGTM!

**Pull request merged**
