### PR TITLE
Updates data-placeholder text for omnibar

### PR DESCRIPTION
**Pull request by caseydoran**
I'd like to see this on .ninja (or rainbow) before we deploy so I can check it on mobile web (since it's so much longer than it was). Thanks!

### CODE REVIEW

**Comment by caseydoran** [comment]
sending this back to copy b/c the copy doesn't make sense for mobile web

**Comment by rynbyjn** [comment]
It wouldn't be hard to switch the placeholder for mobile vs desktop if we want a different variation.

**Comment by rynbyjn** [comment]
@caseydoran is this still a thing, or should we close this out? The immutable branch is going to be merged today hopefully..

**Comment by caseydoran** [comment]
Best PR. Ever.

**Pull request closed without merging**
