### PR TITLE
Set full explicit cookie on log out.

### PR DESCRIPTION
**Pull request by alanpeabody**
Prevent duplicate path specific cookie from getting set.

Fixes https://www.pivotaltracker.com/story/show/141745941

### CODE REVIEW

**Comment by alanpeabody** [comment]
Note: I haven't run this yet to verify.

**Comment by jayzes** [comment]
Good catch!

**Comment by alanpeabody** [comment]
@rynbyjn I can't get webapp to boot locally, good to merge and just verify on staging?

**Comment by rynbyjn** [comment]
@alanpeabody sounds good to me 🤘 . If you were getting and `ENV` error when trying to run the dev server, that should be fixed now on master. If you were trying to run iso you might need to fire up the queue as well..

**Comment by alanpeabody** [comment]
It was the ENV thing, but I think this should be GTG anyway.

**Pull request merged**
