### PR TITLE
Remove iso and set up webpack to deploy to S3

### PR DESCRIPTION
**Pull request by jayzes**
Using https://github.com/MikaAK/s3-plugin-webpack

### CODE REVIEW

**Comment by jayzes** [comment]
Sweet - I rebased off of that as well, looks like it got another change in there from master.

**Comment by ellodanger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a linked tracker story for this PR in the description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by rynbyjn** [comment]
I left it in there for now so `localhost` (still running with node) will still work, but once it is rolled out I can go back and update to use the api version.

**Comment by rynbyjn** [comment]
@alanpeabody that second to last commit (https://github.com/ello/webapp/pull/276/commits/0da7a4512eec9a59446dc5c47410b4b4fd197633) removes the express route for `webapp-token` from the dev server setup and moves over to using the api route 🤘

**Pull request merged**
