### PR TITLE
Guards against window for universal rendering

### PR DESCRIPTION
**Pull request by mkitt**
Fixes https://app.honeybadger.io/projects/47963/faults/32265797

### CODE REVIEW

**Comment by mkitt** [comment]
Created from the immutable branch.

**Comment by jayzes** [comment]
Excellent!

**Comment by mkitt** [comment]
@rynbyjn I thought for some reason you didn't have to on window but I could be wrong. I'll update it with the `typeof` test.

**Comment by mkitt** [comment]
@rynbyjn sure was correct.. fixed to `typeof` in 5eaf55d

**Pull request merged**
