### PR TITLE
Updating project dependencies to the latest

### PR DESCRIPTION
**Pull request by rynbyjn**
Removes overrides for:
* `class-methods-use-this`
* `no-multiple-empty-lines`
* `jsx-a11y/no-static-element-interactions`
* `react/no-danger`
* `no-unused-expressions` in `src` and adds it to `test`

This updates `redux-persist` to `4.0.0-alpha7` which changed the import of the session a bit. Also realized that we were validating the file type twice in uploaders and was able to remove a bunch of the `openAlert` and `closeAlert` methods from `Settings` and `OnboardingSettings`. Biggest change here was removing `for (const value of array)`  in favor of `array.forEach/map/filter/find/some()`

Things to test:
- [x] Search
- [x] Editor hasMention
- [x] Grid/list toggle remembering
- [x] Uploading images in editor, settings, onboarding (test with bad file types too)
- [x] Meta tag images
- [x] Node list forEach

image

[Finishes #134194917](https://www.pivotaltracker.com/story/show/134194917)

### CODE REVIEW

**Comment by jayzes** [comment]
We could trying pointing Heroku at `yarn` as well using this: https://github.com/heroku/heroku-buildpack-nodejs/issues/337#issuecomment-253286196

**Comment by rynbyjn** [comment]
I'm not sure about using `yarn` on production yet as locally it doesn't seem to hold up very well. High memory usage and crashing outright from time to time.. Was basically hoping to gain faster CI runs with this first pass.

**Comment by orta** [comment]
@rynbyjn what did you use to make the screenshot above? ( was thinking of doing something in Danger that would replace [my simple table](https://github.com/artsy/emission/pull/402) )

**Comment by rynbyjn** [comment]
@orta I simply ran `npm outdated` and took a screenshot using `cmd+ctrl+shift+4` on a mac and pasted it here (colors are because of our [dotfiles](https://github.com/ello/dotfiles)). Thanks to github for supporting pasting an image and adding it as markdown! Probably wouldn't really work for the table you generated though..

**Pull request merged**
